### ISSUE TITLE
GD-135: Cannot test signals on non-node classes

### ISSUE THREAD

**Issue by jhlothamer** [MikeSchulze/gdUnit4Net#135]
### The used GdUnit4 version

4.3.3 (Latest Release)

### The used Godot version

v4.3.beta3.mono.official [82cedc83c]

### Operating System

Ubutu 24.04

### Describe the bug

We're converting our GDScript to C# and we have some non-node classes with signals.  The GDScript unit tests written with GDUnit4 work fine.  But the C# unit tests error with the following:

line 0: Unable to cast object of type 'Fulcrum.Class.AgentsBase' to type 'Godot.Node'.

Also note that we are on GDUnit 4.3.4 - the actual latest release.  (Drop down in issue add page does not list this verson.)

### Steps to Reproduce

Add a c# class with a signal based off a non-node class in Godot.
Write GDUnit test for it.
Run test.

```c#
    [TestCase(Timeout = 1000)]
    public async Task EmitSignalOnNoneNodeObjects()
    {
        var emitter = AutoFree(new NonNodeEmitter())!;

        // verify initial the emitters are not monitored
        AssertThat(GodotSignalCollector.Instance.IsSignalCollecting(emitter, NonNodeEmitter.SignalName.SignalA)).IsFalse();


        // start monitoring on the emitter A
        AssertSignal(emitter).StartMonitoring();
     }
     
     public sealed partial class NonNodeEmitter : RefCounted
    {
        [Signal]
        public delegate void SignalAEventHandler();

        public void DoEmitSignalA() => EmitSignal(SignalName.SignalA);
    }
  ```

Error:
```bash
Unable to cast object of type 'NonNodeEmitter' to type 'Godot.Node'.
   at GdUnit4.Core.Signals.GodotSignalCollector.RegisterEmitter(GodotObject emitter) in D:\development\workspace\gdUnit4Net\api\src\core\signals\GodotSignalCollector.cs:line 25
   at GdUnit4.Asserts.SignalAssert..ctor(GodotObject current) in D:\development\workspace\gdUnit4Net\api\src\asserts\SignalAssert.cs:line 13
   at GdUnit4.Assertions.AssertSignal(GodotObject node) in D:\development\workspace\gdUnit4Net\api\src\Assertions.cs:line 98
   at GdUnit4.Tests.Asserts.SignalAssertTest.EmitSignalOnNoneNodeObjects() in D:\development\workspace\gdUnit4Net\test\src\asserts\SignalAssertTest.cs:line 162
   at GdUnit4.Executions.ExecutionStage`1.ExecuteStage(ExecutionContext context) in D:\development\workspace\gdUnit4Net\api\src\core\execution\ExecutionStage.cs:line 146
   at GdUnit4.Executions.ExecutionStage`1.Execute(ExecutionContext context) in D:\development\workspace\gdUnit4Net\api\src\core\execution\ExecutionStage.cs:line 56
```

**Comment by MikeSchulze** [comment]
Thanks for reporting, can you please add an example of your test to reproduce
