### ISSUE TITLE
GD-64: It might be better to use `LaunchProcessWithDebuggerAttached` instead of Start Process and `AttachDebuggerIfNeed`

### ISSUE THREAD

**Issue by van800** [MikeSchulze/gdUnit4Net#64]
Not something critical right now, but I decided to note it down.

**Describe What**
This is the code is in question:
https://github.com/van800/gdUnit4Mono/blob/a9038f91fc33c3a437d39d4714b13a12b06cae5e/testadapter/src/execution/TestExecutor.cs#L84 `GdUnit4.TestAdapter.Execution.TestExecutor.Run`
Consider letting the debugger to start Godot (with LaunchProcessWithDebuggerAttached api) from the very beginning and use the `pid` to get the process to do everything, which you already do now.

**Describe Why**
JIT may apply certain optimizations when the application is started without debugging. This may cause some problems with debugger evaluation of values.

**Comment by MikeSchulze** [comment]
Yes, I already had `LaunchProcessWithDebuggerAttached ` in mind, but had not yet seen any reason to switch to it

**Comment by MikeSchulze** [comment]
I try to swtich to but i run into runtime error.
```
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.VisualStudio.TestWindow.VSCode.Service.TestWindowCallbackService.LaunchDebugTestHostAsync(LaunchTestHostRequest launchRequest, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.CallWithCatchAsync[T](IInternalLogger log, Func`1 func, T defaultValue)
The active test run was aborted. Reason: Exception of type 'Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException' was thrown.
```

So i have no idea whats going wrong here.
From test at runtime it looks like the testhost with Version=15.0.0.0 is loaded but it should be `17.9.0`


`dotnet list package --include-transitive` shows
```bash
   [net8.0]:
   Paket oberster Ebene                      Angefordert   Aufgelöst
   > coverlet.collector                      6.0.0         6.0.0
   > Godot.SourceGenerators                  4.2.1         4.2.1
   > GodotSharp                              4.2.1         4.2.1
   > Microsoft.NET.Test.Sdk                  17.9.0        17.9.0
   > Microsoft.TestPlatform.ObjectModel      17.9.0        17.9.0
   > Newtonsoft.Json                         13.0.3        13.0.3

   Transitives Paket                             Aufgelöst
   > Castle.Core                                 5.1.1
   > CommandLineParser                           2.9.1
   > Microsoft.CodeAnalysis.Analyzers            3.3.4
   > Microsoft.CodeAnalysis.Common               4.9.2
   > Microsoft.CodeAnalysis.CSharp               4.9.2
   > Microsoft.CodeCoverage                      17.9.0
   > Microsoft.TestPlatform.TestHost             17.9.0
   > Moq                                         4.18.4
   > System.Collections.Immutable                8.0.0
   > System.Diagnostics.EventLog                 6.0.0
   > System.Reflection.Metadata                  8.0.0
   > System.Runtime.CompilerServices.Unsafe      6.0.0
   ```
   
   But at runtime 
   ```
        foreach (var referencedAssembly in Assembly.Load("gdUnit4Api").GetReferencedAssemblies())
        {
            frameworkHandle.SendMessage(TestMessageLevel.Informational, $"referencedAssembly {referencedAssembly.FullName}");
        }

        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            frameworkHandle.SendMessage(TestMessageLevel.Informational, $"CurrentDomain {assembly.FullName}");
        }
   ```
   
   ```bash
   referencedAssembly System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
referencedAssembly System.Text.RegularExpressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
referencedAssembly GodotSharp, Version=4.2.1.0, Culture=neutral, PublicKeyToken=null
referencedAssembly System.Collections, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
referencedAssembly System.Linq.Expressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
referencedAssembly System.Diagnostics.StackTrace, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
referencedAssembly Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
referencedAssembly System.Console, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
referencedAssembly System.Drawing.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
referencedAssembly Microsoft.CodeAnalysis, Version=4.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
referencedAssembly Microsoft.CodeAnalysis.CSharp, Version=4.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
referencedAssembly System.Threading, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
referencedAssembly System.Linq, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
referencedAssembly CommandLine, Version=2.9.1.0, Culture=neutral, PublicKeyToken=5a870481e358d379
referencedAssembly System.Memory, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
referencedAssembly Microsoft.CSharp, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
referencedAssembly System.Threading.Thread, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
CurrentDomain testhost, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain Microsoft.TestPlatform.CoreUtilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Diagnostics.Tracing, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Diagnostics.Debug, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Runtime.Extensions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Diagnostics.Process, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.ComponentModel.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain Microsoft.TestPlatform.PlatformAbstractions, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Collections, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain Microsoft.TestPlatform.CrossPlatEngine, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
CurrentDomain Microsoft.TestPlatform.CommunicationUtilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain Microsoft.VisualStudio.TestPlatform.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
CurrentDomain System.Runtime.Serialization.Formatters, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Collections.Concurrent, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Diagnostics.TraceSource, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Threading, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.IO.FileSystem, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Runtime.InteropServices, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Memory, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
CurrentDomain Microsoft.Win32.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Threading.ThreadPool, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Net.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Collections.NonGeneric, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Net.Sockets, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Private.Uri, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Threading.Overlapped, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Runtime.Intrinsics, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
CurrentDomain System.Linq.Expressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Runtime.Numerics, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Linq, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.ComponentModel.TypeConverter, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.ObjectModel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Runtime.Serialization.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Data.Common, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Xml.ReaderWriter, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Private.Xml, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
CurrentDomain System.ComponentModel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Reflection.Emit.ILGeneration, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Reflection.Emit.Lightweight, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Reflection.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
CurrentDomain System.Runtime.Loader, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain gdUnit4.TestAdapter, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null
CurrentDomain System.Reflection.Metadata, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain gdUnit4.TestAdapter, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null
CurrentDomain System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.IO.MemoryMappedFiles, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Text.Encoding.Extensions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Xml.XmlSerializer, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Threading.Thread, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Collections.Specialized, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Reflection.Emit, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain Microsoft.GeneratedCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
CurrentDomain System.Text.RegularExpressions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Console, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Runtime.InteropServices.RuntimeInformation, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Resources.ResourceManager, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Xml.XDocument, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
CurrentDomain System.Private.Xml.Linq, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
CurrentDomain gdUnit4Api, Version=4.2.2.0, Culture=neutral, PublicKeyToken=null
   ````

**Comment by MikeSchulze** [comment]
I can't get any further here at the moment, looks like a C# Dev Kit bug to me.

I open a bug 
https://github.com/microsoft/vscode-dotnettools/issues/1048

**Comment by MikeSchulze** [comment]
The answer shows that https://github.com/microsoft/vscode-dotnettools/issues/1048#issuecomment-2056933777 does not support it.
I tested with JetBrains Rider and encountered the same exception.

So it looks like I am using the right way after all, with `IFrameworkHandle2.AttachDebuggerToProcess`, so I am closing this topic now.
